//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SazonWareBO.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", ConfigurationName="ServicioWS.ServicioWS")]
    public interface ServicioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/insertarGastoRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/insertarGastoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareBO.ServicioWS.insertarGastoResponse insertarGasto(SazonWareBO.ServicioWS.insertarGastoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/insertarGastoRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/insertarGastoResponse")]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.insertarGastoResponse> insertarGastoAsync(SazonWareBO.ServicioWS.insertarGastoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareBO.ServicioWS.listarGastosResponse listarGastos(SazonWareBO.ServicioWS.listarGastosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosResponse")]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.listarGastosResponse> listarGastosAsync(SazonWareBO.ServicioWS.listarGastosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/eliminarGastoRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/eliminarGastoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareBO.ServicioWS.eliminarGastoResponse eliminarGasto(SazonWareBO.ServicioWS.eliminarGastoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/eliminarGastoRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/eliminarGastoResponse")]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.eliminarGastoResponse> eliminarGastoAsync(SazonWareBO.ServicioWS.eliminarGastoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosPorMesRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosPorMesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareBO.ServicioWS.listarGastosPorMesResponse listarGastosPorMes(SazonWareBO.ServicioWS.listarGastosPorMesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosPorMesRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/listarGastosPorMesResponse")]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.listarGastosPorMesResponse> listarGastosPorMesAsync(SazonWareBO.ServicioWS.listarGastosPorMesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/modificarGastoRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/modificarGastoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareBO.ServicioWS.modificarGastoResponse modificarGasto(SazonWareBO.ServicioWS.modificarGastoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/modificarGastoRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/modificarGastoResponse")]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.modificarGastoResponse> modificarGastoAsync(SazonWareBO.ServicioWS.modificarGastoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/obtenerGastoPorIdRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/obtenerGastoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareBO.ServicioWS.obtenerGastoPorIdResponse obtenerGastoPorId(SazonWareBO.ServicioWS.obtenerGastoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gasto.soft.mibanco.pe/ServicioWS/obtenerGastoPorIdRequest", ReplyAction="http://services.gasto.soft.mibanco.pe/ServicioWS/obtenerGastoPorIdResponse")]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.obtenerGastoPorIdResponse> obtenerGastoPorIdAsync(SazonWareBO.ServicioWS.obtenerGastoPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGasto", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class insertarGastoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double monto;
        
        public insertarGastoRequest() {
        }
        
        public insertarGastoRequest(string titulo, string motivo, System.DateTime fecha, double monto) {
            this.titulo = titulo;
            this.motivo = motivo;
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarGastoResponse", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class insertarGastoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarGastoResponse() {
        }
        
        public insertarGastoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gasto.soft.mibanco.pe/")]
    public partial class gasto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idGastoField;
        
        private bool idGastoFieldSpecified;
        
        private double montoField;
        
        private bool montoFieldSpecified;
        
        private string motivoField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idGasto {
            get {
                return this.idGastoField;
            }
            set {
                this.idGastoField = value;
                this.RaisePropertyChanged("idGasto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idGastoSpecified {
            get {
                return this.idGastoFieldSpecified;
            }
            set {
                this.idGastoFieldSpecified = value;
                this.RaisePropertyChanged("idGastoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
                this.RaisePropertyChanged("montoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGastos", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class listarGastosRequest {
        
        public listarGastosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGastosResponse", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class listarGastosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SazonWareBO.ServicioWS.gasto[] @return;
        
        public listarGastosResponse() {
        }
        
        public listarGastosResponse(SazonWareBO.ServicioWS.gasto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGasto", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class eliminarGastoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGasto;
        
        public eliminarGastoRequest() {
        }
        
        public eliminarGastoRequest(int idGasto) {
            this.idGasto = idGasto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarGastoResponse", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class eliminarGastoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarGastoResponse() {
        }
        
        public eliminarGastoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGastosPorMes", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class listarGastosPorMesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anio;
        
        public listarGastosPorMesRequest() {
        }
        
        public listarGastosPorMesRequest(int mes, int anio) {
            this.mes = mes;
            this.anio = anio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGastosPorMesResponse", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class listarGastosPorMesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SazonWareBO.ServicioWS.gasto[] @return;
        
        public listarGastosPorMesResponse() {
        }
        
        public listarGastosPorMesResponse(SazonWareBO.ServicioWS.gasto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGasto", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class modificarGastoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGasto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double monto;
        
        public modificarGastoRequest() {
        }
        
        public modificarGastoRequest(int idGasto, string titulo, string motivo, System.DateTime fecha, double monto) {
            this.idGasto = idGasto;
            this.titulo = titulo;
            this.motivo = motivo;
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarGastoResponse", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class modificarGastoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarGastoResponse() {
        }
        
        public modificarGastoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerGastoPorId", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class obtenerGastoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idGasto;
        
        public obtenerGastoPorIdRequest() {
        }
        
        public obtenerGastoPorIdRequest(int idGasto) {
            this.idGasto = idGasto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerGastoPorIdResponse", WrapperNamespace="http://services.gasto.soft.mibanco.pe/", IsWrapped=true)]
    public partial class obtenerGastoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gasto.soft.mibanco.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SazonWareBO.ServicioWS.gasto @return;
        
        public obtenerGastoPorIdResponse() {
        }
        
        public obtenerGastoPorIdResponse(SazonWareBO.ServicioWS.gasto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWSChannel : SazonWareBO.ServicioWS.ServicioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWSClient : System.ServiceModel.ClientBase<SazonWareBO.ServicioWS.ServicioWS>, SazonWareBO.ServicioWS.ServicioWS {
        
        public ServicioWSClient() {
        }
        
        public ServicioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareBO.ServicioWS.insertarGastoResponse SazonWareBO.ServicioWS.ServicioWS.insertarGasto(SazonWareBO.ServicioWS.insertarGastoRequest request) {
            return base.Channel.insertarGasto(request);
        }
        
        public int insertarGasto(string titulo, string motivo, System.DateTime fecha, double monto) {
            SazonWareBO.ServicioWS.insertarGastoRequest inValue = new SazonWareBO.ServicioWS.insertarGastoRequest();
            inValue.titulo = titulo;
            inValue.motivo = motivo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            SazonWareBO.ServicioWS.insertarGastoResponse retVal = ((SazonWareBO.ServicioWS.ServicioWS)(this)).insertarGasto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.insertarGastoResponse> SazonWareBO.ServicioWS.ServicioWS.insertarGastoAsync(SazonWareBO.ServicioWS.insertarGastoRequest request) {
            return base.Channel.insertarGastoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareBO.ServicioWS.insertarGastoResponse> insertarGastoAsync(string titulo, string motivo, System.DateTime fecha, double monto) {
            SazonWareBO.ServicioWS.insertarGastoRequest inValue = new SazonWareBO.ServicioWS.insertarGastoRequest();
            inValue.titulo = titulo;
            inValue.motivo = motivo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            return ((SazonWareBO.ServicioWS.ServicioWS)(this)).insertarGastoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareBO.ServicioWS.listarGastosResponse SazonWareBO.ServicioWS.ServicioWS.listarGastos(SazonWareBO.ServicioWS.listarGastosRequest request) {
            return base.Channel.listarGastos(request);
        }
        
        public SazonWareBO.ServicioWS.gasto[] listarGastos() {
            SazonWareBO.ServicioWS.listarGastosRequest inValue = new SazonWareBO.ServicioWS.listarGastosRequest();
            SazonWareBO.ServicioWS.listarGastosResponse retVal = ((SazonWareBO.ServicioWS.ServicioWS)(this)).listarGastos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.listarGastosResponse> SazonWareBO.ServicioWS.ServicioWS.listarGastosAsync(SazonWareBO.ServicioWS.listarGastosRequest request) {
            return base.Channel.listarGastosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareBO.ServicioWS.listarGastosResponse> listarGastosAsync() {
            SazonWareBO.ServicioWS.listarGastosRequest inValue = new SazonWareBO.ServicioWS.listarGastosRequest();
            return ((SazonWareBO.ServicioWS.ServicioWS)(this)).listarGastosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareBO.ServicioWS.eliminarGastoResponse SazonWareBO.ServicioWS.ServicioWS.eliminarGasto(SazonWareBO.ServicioWS.eliminarGastoRequest request) {
            return base.Channel.eliminarGasto(request);
        }
        
        public int eliminarGasto(int idGasto) {
            SazonWareBO.ServicioWS.eliminarGastoRequest inValue = new SazonWareBO.ServicioWS.eliminarGastoRequest();
            inValue.idGasto = idGasto;
            SazonWareBO.ServicioWS.eliminarGastoResponse retVal = ((SazonWareBO.ServicioWS.ServicioWS)(this)).eliminarGasto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.eliminarGastoResponse> SazonWareBO.ServicioWS.ServicioWS.eliminarGastoAsync(SazonWareBO.ServicioWS.eliminarGastoRequest request) {
            return base.Channel.eliminarGastoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareBO.ServicioWS.eliminarGastoResponse> eliminarGastoAsync(int idGasto) {
            SazonWareBO.ServicioWS.eliminarGastoRequest inValue = new SazonWareBO.ServicioWS.eliminarGastoRequest();
            inValue.idGasto = idGasto;
            return ((SazonWareBO.ServicioWS.ServicioWS)(this)).eliminarGastoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareBO.ServicioWS.listarGastosPorMesResponse SazonWareBO.ServicioWS.ServicioWS.listarGastosPorMes(SazonWareBO.ServicioWS.listarGastosPorMesRequest request) {
            return base.Channel.listarGastosPorMes(request);
        }
        
        public SazonWareBO.ServicioWS.gasto[] listarGastosPorMes(int mes, int anio) {
            SazonWareBO.ServicioWS.listarGastosPorMesRequest inValue = new SazonWareBO.ServicioWS.listarGastosPorMesRequest();
            inValue.mes = mes;
            inValue.anio = anio;
            SazonWareBO.ServicioWS.listarGastosPorMesResponse retVal = ((SazonWareBO.ServicioWS.ServicioWS)(this)).listarGastosPorMes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.listarGastosPorMesResponse> SazonWareBO.ServicioWS.ServicioWS.listarGastosPorMesAsync(SazonWareBO.ServicioWS.listarGastosPorMesRequest request) {
            return base.Channel.listarGastosPorMesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareBO.ServicioWS.listarGastosPorMesResponse> listarGastosPorMesAsync(int mes, int anio) {
            SazonWareBO.ServicioWS.listarGastosPorMesRequest inValue = new SazonWareBO.ServicioWS.listarGastosPorMesRequest();
            inValue.mes = mes;
            inValue.anio = anio;
            return ((SazonWareBO.ServicioWS.ServicioWS)(this)).listarGastosPorMesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareBO.ServicioWS.modificarGastoResponse SazonWareBO.ServicioWS.ServicioWS.modificarGasto(SazonWareBO.ServicioWS.modificarGastoRequest request) {
            return base.Channel.modificarGasto(request);
        }
        
        public int modificarGasto(int idGasto, string titulo, string motivo, System.DateTime fecha, double monto) {
            SazonWareBO.ServicioWS.modificarGastoRequest inValue = new SazonWareBO.ServicioWS.modificarGastoRequest();
            inValue.idGasto = idGasto;
            inValue.titulo = titulo;
            inValue.motivo = motivo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            SazonWareBO.ServicioWS.modificarGastoResponse retVal = ((SazonWareBO.ServicioWS.ServicioWS)(this)).modificarGasto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.modificarGastoResponse> SazonWareBO.ServicioWS.ServicioWS.modificarGastoAsync(SazonWareBO.ServicioWS.modificarGastoRequest request) {
            return base.Channel.modificarGastoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareBO.ServicioWS.modificarGastoResponse> modificarGastoAsync(int idGasto, string titulo, string motivo, System.DateTime fecha, double monto) {
            SazonWareBO.ServicioWS.modificarGastoRequest inValue = new SazonWareBO.ServicioWS.modificarGastoRequest();
            inValue.idGasto = idGasto;
            inValue.titulo = titulo;
            inValue.motivo = motivo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            return ((SazonWareBO.ServicioWS.ServicioWS)(this)).modificarGastoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareBO.ServicioWS.obtenerGastoPorIdResponse SazonWareBO.ServicioWS.ServicioWS.obtenerGastoPorId(SazonWareBO.ServicioWS.obtenerGastoPorIdRequest request) {
            return base.Channel.obtenerGastoPorId(request);
        }
        
        public SazonWareBO.ServicioWS.gasto obtenerGastoPorId(int idGasto) {
            SazonWareBO.ServicioWS.obtenerGastoPorIdRequest inValue = new SazonWareBO.ServicioWS.obtenerGastoPorIdRequest();
            inValue.idGasto = idGasto;
            SazonWareBO.ServicioWS.obtenerGastoPorIdResponse retVal = ((SazonWareBO.ServicioWS.ServicioWS)(this)).obtenerGastoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareBO.ServicioWS.obtenerGastoPorIdResponse> SazonWareBO.ServicioWS.ServicioWS.obtenerGastoPorIdAsync(SazonWareBO.ServicioWS.obtenerGastoPorIdRequest request) {
            return base.Channel.obtenerGastoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareBO.ServicioWS.obtenerGastoPorIdResponse> obtenerGastoPorIdAsync(int idGasto) {
            SazonWareBO.ServicioWS.obtenerGastoPorIdRequest inValue = new SazonWareBO.ServicioWS.obtenerGastoPorIdRequest();
            inValue.idGasto = idGasto;
            return ((SazonWareBO.ServicioWS.ServicioWS)(this)).obtenerGastoPorIdAsync(inValue);
        }
    }
}
